docs: rather .expect than .unwrap where the code can fail
Avoid "thread ... panicked at <file>.rs:24:28; called `Result::unwrap()`
on an `Err` value: "<error>""
But: "thread ... panicked at <file>.rs:24:28;
"<your_expect_message>":<error>"
You can put the function name, and why it is not supposed to panic. It
will avoid to have a look inside the file to see why it has panic